Cumulus-497 Added protocol for https
cumulus-nasa/cumulus-integration-tests pull request #19
Opened 2018-04-12 18:55 UTC by kkelly51

2018-04-12 19:59 UTC, laurenfrederick requested changes

2018-04-12 19:59 UTC, laurenfrederick commented on spec/discoverGranules/DiscoverGranulesSuccessSpec.js
> +    httpWorkflowExecution = await executeWorkflow(
I think http and https should be separate tests, so put in a separate top level `describe` statement.

2018-04-13 15:46 UTC, scisco commented
I'm going to move this PR to the cumulus repo after [this PR](https://github.com/cumulus-nasa/cumulus/pull/299) is merged.

2018-04-13 16:38 UTC, laurenfrederick approved these changes

2018-04-16 18:25 UTC, scisco commented
Moved to cumulus repo

2018-04-16 18:25 UTC, closed without merging